name: parallel_modflow
channels:
  - conda-forge
dependencies:
  # required
  - python>=3.8
  - numpy>=1.15.0
  - matplotlib>=1.4.0

  # optional
  - python-dateutil>=2.4.0
  - affine
  - scipy
  - pandas
  - pyshp
  - rasterio
  - fiona
  - descartes
  - pyproj
  - shapely>=1.8
  - geos
  - geojson
  - vtk
  - rasterstats
  - pyvista
  - imageio
  - pymetis

  # MODFLOW API dependencies
  - bmipy

  # pip installations
  - pip
  - pip:
      - git+https://github.com/modflowpy/flopy.git
      - git+https://github.com/modflowpy/pymake.git
      - git+https://github.com/Deltares/xmipy.git
      - git+https://github.com/MODFLOW-USGS/modflowapi.git
      - modflow-devtools
